Repository coverlet-coverage/coverlet, pull requests merged in 2019-09, with the labels that each got.

#526 Add switch test
  src/coverlet.core/Instrumentation/InstrumenterResult.cs
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
  test/coverlet.core.tests/Samples/Instrumentation.SelectionStatements.cs
  test/coverlet.core.tests/Samples/Instrumentation.cs
Labels: enhancement

#527 Improve instrumentation tests
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Samples/Samples.cs
Labels: enhancement

#524 Fix exclude by files
  src/coverlet.core/Coverage.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/coverlet.core.csproj
  test/coverlet.core.tests/Helpers/InstrumentationHelperTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
Labels: bug

#531 Inject InstrumentationHelper
  src/coverlet.collector/DataCollection/CoverageWrapper.cs
  src/coverlet.console/Program.cs
  src/coverlet.core/Abstracts/InstrumentationHelper.cs
  src/coverlet.core/Coverage.cs
  src/coverlet.core/DependencyInjection.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.msbuild.tasks/CoverageResultTask.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
  test/coverlet.collector.tests/CoverletCoverageDataCollectorTests.cs
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/Helpers/InstrumentationHelperTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
Labels: enhancement

#540 Add examples on guide
  Documentation/Examples.md
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary1/Class1.cs
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary1/ClassLibrary1.csproj
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary2/Class2.cs
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary2/ClassLibrary2.csproj
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary3/Class3.cs
  Documentation/Examples/MSBuild/MergeWith/ClassLibrary3/ClassLibrary3.csproj
  Documentation/Examples/MSBuild/MergeWith/MergeWith.md
  Documentation/Examples/MSBuild/MergeWith/MergeWith.sln
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject1/UnitTest1.cs
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject1/XUnitTestProject1.csproj
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject2/UnitTest2.cs
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject2/XUnitTestProject2.csproj
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject3/UnitTest3.cs
  Documentation/Examples/MSBuild/MergeWith/XUnitTestProject3/XUnitTestProject3.csproj
  README.md
Labels: documentation

#538 Skip instrumentation for external pdb with no local sources
  src/coverlet.core/Abstracts/IFileSystem.cs
  src/coverlet.core/Abstracts/IInstrumentationHelper.cs
  src/coverlet.core/DependencyInjection.cs
  src/coverlet.core/Helpers/FileSystem.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/Properties/AssemblyInfo.cs
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/Helpers/InstrumentationHelperTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
Labels: enhancement

#533 [Collectors]Output multiple formats
  Documentation/VSTestIntegration.md
  src/coverlet.collector/DataCollection/AttachmentManager.cs
  src/coverlet.collector/DataCollection/CoverageManager.cs
  src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs
  src/coverlet.collector/DataCollection/CoverletSettings.cs
  src/coverlet.collector/DataCollection/CoverletSettingsParser.cs
  src/coverlet.collector/Utilities/CountDownEvent.cs
  src/coverlet.collector/Utilities/Interfaces/ICountDown.cs
  src/coverlet.collector/Utilities/TestPlatformEqtTrace.cs
  src/coverlet.collector/Utilities/TestPlatformLogger.cs
  src/coverlet.core/Reporters/ReporterFactory.cs
  test/coverlet.collector.tests/AttachmentManagerTests.cs
  test/coverlet.collector.tests/CoverletCoverageDataCollectorTests.cs
  test/coverlet.collector.tests/CoverletSettingsParserTests.cs
  test/coverlet.collector.tests/coverlet.collector.tests.csproj
Labels: feature-request

#545 Fix nightly build
  eng/azure-pipelines-nightly.yml
Labels: infrastructure

#535 Update guide for inproc collector
  README.md
Labels: documentation

#558 Fix source file check for non portable pdb
  src/coverlet.core/Coverage.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
Labels: bug

#550 SystemIOFile Adapter
  src/coverlet.collector/DataCollection/CoverageWrapper.cs
  src/coverlet.console/Program.cs
  src/coverlet.core/Abstracts/IFileSystem.cs
  src/coverlet.core/Coverage.cs
  src/coverlet.core/Helpers/FileSystem.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.msbuild.tasks/CoverageResultTask.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
  test/coverlet.collector.tests/CoverletCoverageDataCollectorTests.cs
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
Labels: enhancement

#564 Update release plan
  Documentation/ReleasePlan.md
Labels: documentation

#552 Improve in-proc collector logs
  Documentation/Troubleshooting.md
  src/coverlet.collector/InProcDataCollection/CoverletInProcDataCollector.cs
  src/coverlet.collector/Utilities/TestPlatformEqtTrace.cs
Labels: documentation, enhancement

#553 Add log to tracker
  Documentation/Troubleshooting.md
  src/coverlet.core/Coverage.cs
  src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
Labels: enhancement

#549 Fix and simplify async coverage
  src/coverlet.core/Coverage.cs
  src/coverlet.core/CoverageResult.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/Instrumentation/InstrumenterResult.cs
  src/coverlet.core/Symbols/BranchPoint.cs
  src/coverlet.core/Symbols/CecilSymbolHelper.cs
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterResultTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
  test/coverlet.core.tests/Samples/Instrumentation.AsyncAwait.cs
  test/coverlet.core.tests/Samples/Samples.cs
  test/coverlet.core.tests/Symbols/CecilSymbolHelperTests.cs
Labels: bug, tenet-coverage

#565 Rethink SkipEmbeddedPpdbWithoutLocalSource and SkipPpdbWithoutLocalSource tests, are flaky on CI
  coverlet.sln
  src/coverlet.core/Helpers/FileSystem.cs
  test/coverlet.core.tests/.gitignore
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/TestAssets/75d9f96508d74def860a568f426ea4a4.dll
  test/coverlet.core.tests/TestAssets/75d9f96508d74def860a568f426ea4a4.pdb
  test/coverlet.core.tests/coverlet.core.tests.csproj
  test/coverlet.tests.projectsample.empty/Class1.cs
  test/coverlet.tests.projectsample.empty/coverlet.tests.projectsample.empty.csproj
Labels: test bug

#567 Fix countdown event wait
  src/coverlet.collector/Utilities/CountDownEvent.cs
Labels: enhancement

#568 Update "mergewith" doc
  Documentation/GlobalTool.md
  Documentation/MSBuildIntegration.md
  Documentation/VSTestIntegration.md
Labels: documentation

#569 Improve exception message
  src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs
Labels: enhancement
