Repository coverlet-coverage/coverlet, pull requests merged in 2019-06, with the labels that each got.

#467 Update requirements on docs
  README.md
Labels: documentation

#445 Replace AppVeyor badge with Azure Pipelines
  README.md
Labels: documentation

#443 Build to bin\<config>\Packages instead of build\
  Directory.Build.props
  azure-pipelines.yml
  eng/nightly.ps1
Labels: infrastructure

#458 [Bug fix]Fix instrumentation serialization bug
  Documentation/Troubleshooting.md
  src/coverlet.core/CoveragePrepareResult.cs
  src/coverlet.core/Instrumentation/InstrumenterResult.cs
  src/coverlet.core/coverlet.core.csproj
  test/coverlet.core.tests/Instrumentation/InstrumenterResultTests.cs
Labels: bug

#464 [Bug fix]Fix culture for cobertura xml report
  src/coverlet.core/Reporters/CoberturaReporter.cs
  test/coverlet.core.tests/Reporters/CoberturaReporterTests.cs
Labels: bug

#446 Add nuget.config file
  nuget.config
Labels: enhancement, infrastructure

#442 Index sources into PDBs
  .gitignore
  Directory.Build.props
  azure-pipelines.yml
  src/coverlet.collector/coverlet.collector.csproj
  src/coverlet.console/coverlet.console.csproj
  src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj
Labels: enhancement, infrastructure

#412 Different exit codes to indicate particular failures
  src/coverlet.console/ExitCodes.cs
  src/coverlet.console/Program.cs
Labels: enhancement

#478 Adding exit codes information to global tool documentation
  Documentation/GlobalTool.md
Labels: * NO MERGE *, enhancement

#454 Add "Consume nightly build" docs
  Documentation/ConsumeNightlyBuild.md
  Documentation/images/nightly.PNG
  Documentation/images/nightly_1.PNG
  Documentation/images/nightly_2.PNG
  README.md
Labels: documentation
