Repository coverlet-coverage/coverlet, pull requests merged in 2019-08, with the labels that each got.

#512 Using solution wide Directory.Build.targets
  Directory.Build.targets
  src/coverlet.collector/coverlet.collector.csproj
  src/coverlet.console/coverlet.console.csproj
  src/coverlet.core/coverlet.core.csproj
  src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj
  test/Directory.Build.targets
  test/coverlet.collector.tests/coverlet.collector.tests.csproj
  test/coverlet.core.performancetest/coverlet.core.performancetest.csproj
  test/coverlet.core.tests/coverlet.core.tests.csproj
Labels: enhancement

#514 Cleanup deprecated dotnet-xunit tool
  test/coverlet.collector.tests/coverlet.collector.tests.csproj
  test/coverlet.core.tests/coverlet.core.tests.csproj
Labels: enhancement, infrastructure

#420 Improve instrumentation tests
  Directory.Build.targets
  coverlet.sln
  src/coverlet.core/Abstracts/IProcessExitHandler.cs
  src/coverlet.core/Abstracts/IRetryHelper.cs
  src/coverlet.core/DependencyInjection.cs
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Helpers/ProcessExitHandler.cs
  src/coverlet.core/Helpers/RetryHelper.cs
  src/coverlet.core/coverlet.core.csproj
  test/coverlet.collector.tests/coverlet.collector.tests.csproj
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/Helpers/RetryHelperTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
  test/coverlet.core.tests/Samples/Instrumentation.cs
  test/coverlet.core.tests/coverlet.core.tests.csproj
  test/coverlet.tests.remoteexecutor/Program.cs
  test/coverlet.tests.remoteexecutor/Properties/AssemblyInfo.cs
  test/coverlet.tests.remoteexecutor/RemoteExecutor.cs
  test/coverlet.tests.remoteexecutor/coverlet.tests.remoteexecutor.csproj
  test/coverlet.tests.remoteexecutor/coverlet.tests.remoteexecutor.snk
Labels: enhancement

#515 Update guide
  README.md
Labels: documentation

#505 Fix missing quotation mark for test command
  CONTRIBUTING.md
Labels: documentation

#510 Skip instrumentation of module with embedded ppbd without local sources
  src/coverlet.core/Helpers/InstrumentationHelper.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  test/coverlet.core.tests/Helpers/InstrumentationHelperTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
Labels: enhancement

#518 Add ReportGenerator helper
  Directory.Build.targets
  test/coverlet.core.tests/CoverageTests.cs
  test/coverlet.core.tests/InstrumenterHelper.cs
  test/coverlet.core.tests/coverlet.core.tests.csproj
Labels: enhancement

#517 Improve dotnet tool output
  src/coverlet.console/Program.cs
Labels: enhancement

#522 Update collector docs
  Documentation/VSTestIntegration.md
Labels: documentation

#519 Revert "Add `[xunit*]*` to default excluded modules filter if not specified"
  src/coverlet.collector/DataCollection/CoverletSettingsParser.cs
  src/coverlet.console/Program.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
  test/coverlet.collector.tests/CoverletSettingsParserTests.cs
Labels: enhancement
