Repository coverlet-coverage/coverlet, pull requests merged in 2019-07, with the labels that each got.

#477 Fix property attribute detection
  src/coverlet.core/Instrumentation/Instrumenter.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Samples/Samples.cs
Labels: bug

#487 Add a major roll-forward policy
  src/coverlet.console/runtimeconfig.template.json
Labels: enhancement

#481 Fixed index out of range bug in CoberturaReporter when method name has two double-colons
  src/coverlet.core/Reporters/CoberturaReporter.cs
  test/coverlet.core.tests/Reporters/CoberturaReporterTests.cs
Labels: bug

#498 Revert "Using File.Exists for HitsFile creation/update validation"
  src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs
Labels: bug

#493 fixing TeamCity Service Messages
  Documentation/GlobalTool.md
  Documentation/MSBuildIntegration.md
  src/coverlet.core/Reporters/TeamCityReporter.cs
  test/coverlet.core.tests/Reporters/TeamCityReporter.cs
Labels: bug

#479 Changed to calculate based on the average coverage of the modules
  src/coverlet.console/Program.cs
  src/coverlet.core/CoverageDetails.cs
  src/coverlet.core/CoverageResult.cs
  src/coverlet.core/CoverageSummary.cs
  test/coverlet.core.tests/CoverageSummaryTests.cs
Labels: bug

#450 Add release plan
  Documentation/ReleasePlan.md
Labels: documentation

#508 Upgrade Mono.Cecil to avoid re-order of attributes on re-write.
  src/coverlet.core/coverlet.core.csproj
Labels: bug
