Repository coverlet-coverage/coverlet, pull requests merged in 2020-01, with the labels that each got.

#687 Allow different test sdk test
  test/coverlet.integration.tests/BaseTest.cs
  test/coverlet.integration.tests/Collectors.cs
  test/coverlet.integration.tests/DotnetTool.cs
  test/coverlet.integration.tests/Msbuild.cs
Labels: enhancement

#688 Move/Pin to 3.1 runtime
  CONTRIBUTING.md
  Directory.Build.props
  _assets/coverlet-icon.png
  eng/build.yml
  global.json
  src/coverlet.collector/coverlet.collector.csproj
  src/coverlet.console/coverlet.console.csproj
  src/coverlet.core/coverlet.core.csproj
  src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj
  test/coverlet.collector.tests/coverlet.collector.tests.csproj
  test/coverlet.core.performancetest/coverlet.core.performancetest.csproj
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/coverlet.core.tests.csproj
  test/coverlet.integration.template/coverlet.integration.template.csproj
  test/coverlet.integration.tests/BaseTest.cs
  test/coverlet.integration.tests/coverlet.integration.tests.csproj
  test/coverlet.tests.projectsample.excludedbyattribute/coverlet.tests.projectsample.excludedbyattribute.csproj
  test/coverlet.tests.remoteexecutor/coverlet.tests.remoteexecutor.csproj
  test/coverlet.testsubject/coverlet.testsubject.csproj
Labels: enhancement, infrastructure

#671 Avoid to instrument compiler generated code when generated from excluded methods
  src/coverlet.core/Instrumentation/Instrumenter.cs
  test/coverlet.core.tests/Coverage/CoverageTests.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
  test/coverlet.core.tests/Helpers/InstrumentationHelperTests.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFromCoverage.Issue670.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFromCoverage.NestedStateMachines.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFromCoverage.cs
Labels: bug, tenet-coverage

#679 Trim whitespace between values when reading from configuration from runsettings
  src/coverlet.collector/DataCollection/CoverletSettingsParser.cs
  test/coverlet.collector.tests/CoverletSettingsParserTests.cs
Labels: enhancement

#694 Check nested types for exclude filter
  Directory.Build.targets
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs
  test/coverlet.core.tests/Coverage/CoverageTests.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Instrumentation/ModuleTrackerTemplateTests.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFilter.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFromCoverage.cs
  test/coverlet.core.tests/TestAssets/System.Private.CoreLib.dll
  test/coverlet.core.tests/TestAssets/System.Private.CoreLib.pdb
  test/coverlet.core.tests/coverlet.core.tests.csproj
  test/coverlet.integration.tests/BaseTest.cs
  test/coverlet.tests.remoteexecutor/RemoteExecutor.cs
Labels: bug

#698 Improve coverage of async/await state machine
  Directory.Build.targets
  coverlet.sln
  eng/build.yml
  src/coverlet.core/Symbols/CecilSymbolHelper.cs
  test/coverlet.core.tests.samples.netstandard/Instrumentation.AsyncAwait.cs
  test/coverlet.core.tests.samples.netstandard/coverlet.core.tests.samples.netstandard.csproj
  test/coverlet.core.tests/Coverage/CoverageTests.AsyncAwait.cs
  test/coverlet.core.tests/Coverage/CoverageTests.ExcludeFromCoverageAttribute.cs
  test/coverlet.core.tests/Coverage/CoverageTests.Filters.cs
  test/coverlet.core.tests/Coverage/CoverageTests.Lambda.cs
  test/coverlet.core.tests/Coverage/CoverageTests.SelectionStatements.cs
  test/coverlet.core.tests/Coverage/CoverageTests.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
  test/coverlet.core.tests/Samples/Instrumentation.AsyncAwait.cs
  test/coverlet.core.tests/coverlet.core.tests.csproj
Labels: bug, tenet-coverage

#702 Improve branch detection for lambda functions and async/await statements
  src/coverlet.core/Symbols/CecilSymbolHelper.cs
  test/coverlet.core.tests/Coverage/CoverageTests.Lambda.cs
Labels: bug, tenet-coverage
