Repository coverlet-coverage/coverlet, pull requests merged in 2020-05, with the labels that each got.

#832 Add roadmap
  Documentation/Roadmap.md
  README.md
Labels: discussion

#835 Avoid double flush hit files for collectors
  Documentation/Examples/VSTest/HelloWorld/XUnitTestProject1/XUnitTestProject1.csproj
  src/coverlet.collector/InProcDataCollection/CoverletInProcDataCollector.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
  test/coverlet.core.tests/Instrumentation/ModuleTrackerTemplateTests.cs
Labels: bug, driver-collectors

#768 Refactore DependencyInjection
  src/coverlet.collector/DataCollection/CoverageWrapper.cs
  src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs
  src/coverlet.console/Program.cs
  src/coverlet.core/DependencyInjection.cs
  src/coverlet.core/Extensions/DependencyInjectionExtensions.cs
  src/coverlet.msbuild.tasks/BaseTask.cs
  src/coverlet.msbuild.tasks/CoverageResultTask.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
Labels: enhancement

#813 Skip branches in generated `MoveNext()` for singleton iterators
  src/coverlet.core/Symbols/CecilSymbolHelper.cs
  test/coverlet.core.tests/Coverage/CoverageTest.Yield.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.Assertions.cs
  test/coverlet.core.tests/Samples/Instrumentation.Yield.cs
  test/coverlet.core.tests/Samples/Samples.cs
  test/coverlet.core.tests/Symbols/CecilSymbolHelperTests.cs
Labels: bug, tenet-coverage

#849 Fix skip [ExcludefromCoverage] for generated async state machine
  src/coverlet.core/Instrumentation/Instrumenter.cs
  test/coverlet.core.tests/Coverage/CoverageTests.ExcludeFromCoverageAttribute.cs
  test/coverlet.core.tests/Samples/Instrumentation.ExcludeFromCoverage.Issue809.cs
  test/coverlet.core.tests/coverlet.core.tests.csproj
Labels: bug, tenet-coverage

#858 Fix package links
  eng/azure-pipelines-nightly.yml
  eng/build.yml
  global.json
  src/coverlet.collector/coverlet.collector.csproj
  src/coverlet.console/coverlet.console.csproj
  src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj
Labels: infrastructure
