Repository coverlet-coverage/coverlet, pull requests merged in 2020-06, with the labels that each got.

#866 Update KnownIssues.md
  Documentation/KnownIssues.md
Labels: documentation

#846 Change CecilSymbolHelper to instance class
  src/coverlet.collector/DataCollection/CoverageManager.cs
  src/coverlet.collector/DataCollection/CoverageWrapper.cs
  src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs
  src/coverlet.collector/Utilities/Interfaces/ICoverageWrapper.cs
  src/coverlet.console/Program.cs
  src/coverlet.core/Abstractions/ICecilSymbolHelper.cs
  src/coverlet.core/Coverage.cs
  src/coverlet.core/Instrumentation/Instrumenter.cs
  src/coverlet.core/Symbols/CecilSymbolHelper.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
  test/coverlet.collector.tests/CoverletCoverageDataCollectorTests.cs
  test/coverlet.core.tests/Coverage/CoverageTests.ExcludeFromCoverageAttribute.cs
  test/coverlet.core.tests/Coverage/CoverageTests.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Symbols/CecilSymbolHelperTests.cs
Labels: enhancement

#876 Refactor coverage parameters
  src/coverlet.collector/DataCollection/CoverageWrapper.cs
  src/coverlet.console/Program.cs
  src/coverlet.core/Coverage.cs
  src/coverlet.msbuild.tasks/InstrumentationTask.cs
  test/coverlet.collector.tests/CoverletCoverageDataCollectorTests.cs
  test/coverlet.core.tests/Coverage/CoverageTests.ExcludeFromCoverageAttribute.cs
  test/coverlet.core.tests/Coverage/CoverageTests.cs
  test/coverlet.core.tests/Coverage/InstrumenterHelper.cs
Labels: enhancement

#884 Fix attribute exclusion
  Documentation/MSBuildIntegration.md
  src/coverlet.core/Instrumentation/Instrumenter.cs
  test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs
  test/coverlet.core.tests/Samples/Samples.cs
  test/coverlet.core.tests/Symbols/CecilSymbolHelperTests.cs
Labels: bug
